file = {
    "lua/today/core/dates/init.lua",
    "lua/today/core/dates/dateobj.lua",
    "lua/today/core/dates/natural.lua",
    "lua/today/core/dates/recurring.lua",
    "lua/today/core/update.lua",
    "lua/today/core/categorizers.lua",
    "lua/today/core/informers.lua",
    "lua/today/core/filterers.lua",
    "lua/today/core/sort.lua",
    "lua/today/core/task.lua",
    "lua/today/ui.lua",
    "lua/today/util.lua",
}

package = "lua/today"

format = "markdown"

project = "today.nvim"
